default_settings: null
behaviors:
  CollabRLCu_Curriculum_Reward_Full:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.0003
        encoding_size: null
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 30000
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters:
  room_count:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3005
          value: 2
      name: TwoRoomsStatic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 50
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3006
          value: 2
      name: TwoRoomsDynamic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3007
          value: 3
      name: ThreeRoomsStatic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3008
          value: 3
      name: ThreeRoomsDynamic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 200
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3009
          value: 4
      name: FourRoomsStatic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3010
          value: 4
      name: FourRoomsDynamic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 300
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3011
          value: 5
      name: FiveRoomsStatic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3012
          value: 5
      name: FiveRoomsDynamic
      completion_criteria: null
  should_randomize:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3013
          value: 0
      name: TwoRoomsStatic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 50
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3014
          value: 1
      name: TwoRoomsDynamic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3015
          value: 0
      name: ThreeRoomsStatic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3016
          value: 1
      name: ThreeRoomsDynamic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 200
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3017
          value: 0
      name: FourRoomsStatic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3018
          value: 1
      name: FourRoomsDynamic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 300
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3019
          value: 0
      name: FiveRoomsStatic
      completion_criteria:
        behavior: CollabRLCu_Curriculum_Reward_Full
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 5.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3020
          value: 1
      name: FiveRoomsDynamic
      completion_criteria: null
checkpoint_settings:
  run_id: CollabRLCu_Curriculum_Reward_Full_v2_01
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
