behaviors:
  CollabILDoor:
      trainer_type: ppo
      time_horizon: 128
      max_steps: 1.0e7
      hyperparameters:
        batch_size: 128
        buffer_size: 2048
        learning_rate: 0.0003
        beta: 0.01
        epsilon: 0.2
        lambd: 0.95
        num_epoch: 3
        learning_rate_schedule: linear
      network_settings:
        num_layers: 2
        normalize: false
        hidden_units: 512
        vis_encode_type: simple
      reward_signals:
        extrinsic:
          strength: 1.0
          gamma: 0.99
        gail:
          strength: 0.01
          gamma: 0.99
          demo_path: Demos/SingleModelCollab.demo
      behavioral_cloning:
        demo_path: Demos/SingleModelCollab.demo
        strength: 0.5
        steps: 150000
      keep_checkpoints: 5
      max_steps: 5000000
      time_horizon: 128
      summary_freq: 30000
      threaded: true
  CollabILNoDoor:
    trainer_type: ppo
    time_horizon: 128
    max_steps: 1.0e7
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 512
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      gail:
        strength: 0.01
        gamma: 0.99
        demo_path: Demos/CollabNoDoor.demo
    behavioral_cloning:
      demo_path: Demos/CollabNoDoor.demo
      strength: 0.5
      steps: 150000
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 30000
    threaded: true
  CollabILCu:
    trainer_type: ppo
    time_horizon: 128
    max_steps: 1.0e7
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 512
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      gail:
        strength: 0.01
        gamma: 0.99
        demo_path: Demos/SingleModelCollab.demo
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 256
    behavioral_cloning:
      demo_path: Demos/SingleModelCollab.demo
      strength: 0.5
      steps: 150000
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 30000
    threaded: true
  CollabRL:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 30000
    threaded: true
  CollabRLOnly:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 30000
    threaded: true
