behaviors:
  CollabRLCu_NoLearning:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 0.000000001
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
    keep_checkpoints: 5
    max_steps: 5500000
    time_horizon: 128
    summary_freq: 30000
    threaded: true
# environment_parameters:
#   room_count:
#       sampler_type: uniform
#       sampler_parameters:
#         min_value: 2
#         max_value: 5
#   should_randomize: 1
        
      