behaviors:
  CollabRLCu_Curriculum:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 30000
    threaded: true
environment_parameters:
  room_count:
    curriculum:
      - name: TwoRooms
        value: 2
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          signal_smoothing: true
          threshold: 0.1
          min_lesson_length: 100
      - name: ThreeRooms
        value: 3
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          threshold: 0.25
          min_lesson_length: 100
      - name: FourRooms
        value: 4
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          threshold: 0.5
          min_lesson_length: 100
      - name: FiveRooms
        value: 5
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          threshold: 0.9
          min_lesson_length: 100
      - name: RandomRooms
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 2
            max_value: 5
  should_randomize:
    curriculum:
      - name: Static2Rooms
        value: 0
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          threshold: 0.05
          signal_smoothing: true
          min_lesson_length: 100
      - name: Dynamic2Rooms
        value: 1
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          threshold: 0.1
          signal_smoothing: true
          min_lesson_length: 100
      - name: Static3Rooms
        value: 0
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          threshold: 0.15
          signal_smoothing: true
          min_lesson_length: 100
      - name: Dynamic3Rooms
        value: 1
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          threshold: 0.25
          signal_smoothing: true
          min_lesson_length: 100
      - name: Static4Rooms
        value: 0
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          threshold: 0.35
          signal_smoothing: true
          min_lesson_length: 100
      - name: Dynamic4Rooms
        value: 1
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          threshold: 0.5
          signal_smoothing: true
          min_lesson_length: 100
      - name: Static5Rooms
        value: 0
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          threshold: 0.7
          signal_smoothing: true
          min_lesson_length: 100
      - name: Dynamic5Rooms
        value: 1
        completion_criteria:
          measure: progress
          behavior: CollabRLCu_Curriculum
          threshold: 0.9
          signal_smoothing: true
          min_lesson_length: 100
      - name: FinalRandomization
        value: 1