behaviors:
  CollabRLCu_Curriculum_Reward_Full:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 3000000
    time_horizon: 128
    summary_freq: 30000
    threaded: true
environment_parameters:
    room_count:
    curriculum:
      - name: TwoRoomsStatic
        value: 2
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          signal_smoothing: true
          threshold: 5
          min_lesson_length: 100
      - name: TwoRoomsDynamic
        value: 2
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 5
          min_lesson_length: 100
      - name: ThreeRoomsStatic
        value: 3
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 5
          min_lesson_length: 100
      - name: ThreeRoomsDynamic
        value: 3
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 5
          min_lesson_length: 100
      - name: FourRoomsStatic
        value: 4
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 5
          min_lesson_length: 100
      - name: FourRoomsDynamic
        value: 4
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 4.8
          min_lesson_length: 100
      - name: FiveRoomsStatic
        value: 5
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 5
          min_lesson_length: 100
      - name: FiveRoomsDynamic
        value: 5
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 4.7
          min_lesson_length: 100
      - name: RandomRooms
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 2
            max_value: 5
  should_randomize:
    curriculum:
      - name: TwoRoomsStatic
        value: 0
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 5
          signal_smoothing: true
          min_lesson_length: 100
      - name: TwoRoomsDynamic
        value: 1
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 5
          signal_smoothing: true
          min_lesson_length: 100
      - name: ThreeRoomsStatic
        value: 0
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 5
          signal_smoothing: true
          min_lesson_length: 100
      - name: ThreeRoomsDynamic
        value: 1
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 5
          signal_smoothing: true
          min_lesson_length: 100
      - name: FourRoomsStatic
        value: 0
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 5
          signal_smoothing: true
          min_lesson_length: 100
      - name: FourRoomsDynamic
        value: 1
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 4.8
          signal_smoothing: true
          min_lesson_length: 100
      - name: FiveRoomsStatic
        value: 0
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 5
          signal_smoothing: true
          min_lesson_length: 100
      - name: FiveRoomsDynamic
        value: 1
        completion_criteria:
          measure: reward
          behavior: CollabRLCu_Curriculum_Reward_Full
          threshold: 4.7
          signal_smoothing: true
          min_lesson_length: 100
      - name: Always
        value: 1
        